version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    assignees:
      - "bobeal"
    target-branch: "develop"
    groups:
      nifi:
        patterns:
          - "org.apache.nifi*"
