package egm.io.nifi.processors.ckan.ngsild;

public final class NGSIConstants {

    // Common fields for sinks
    public static final String RECV_TIME_TS = "recvTimeTs";
    public static final String RECV_TIME = "recvTime";
    public static final String ENTITY_ID = "entityId";
    public static final String ENTITY_TYPE = "entityType";

    public static final String AUTOGENERATED_ATTR_TYPE = "_attr_internal_type";

    // NGSI-LD constants
    public static final String NGSILD_ID = "id";
    public static final String NGSILD_CREATED_AT = "createdAt";
    public static final String NGSILD_MODIFIED_AT = "modifiedAt";
    public static final String NGSILD_OBSERVED_AT = "observedAt";
    public static final String NGSILD_TYPE = "type";
    public static final String NGSILD_VALUE = "value";
    public static final String NGSILD_OBJECT = "object";
    public static final String NGSILD_JSON = "json";
    public static final String NGSILD_UNIT_CODE = "unitCode";
    public static final String NGSILD_CONTEXT = "@context";
    public static final String NGSILD_PROPERTY = "Property";
    public static final String NGSILD_RELATIONSHIP = "Relationship";
    public static final String NGSILD_GEOPROPERTY = "GeoProperty";
    public static final String NGSILD_DATA = "data";
    public static final String NGSILD_DATASET_ID = "datasetId";

    // DCAT specific attributes
    public static final String DCAT_SERVES_DATASET = "servesDataset";
    public static final String DCAT_PUBLISHER_URL = "publisherURL";

    // JSON-LD format
    public static final String JSON_LD_FORMAT = "application/ld+json";

    // NGSICKANSink specific constants
    // http://docs.ckan.org/en/latest/api/#ckan.logic.action.create.organization_create
    // http://docs.ckan.org/en/latest/api/#ckan.logic.action.create.package_create
    public static final int CKAN_MAX_NAME_LEN = 100;
    public static final int CKAN_MIN_NAME_LEN = 2;

    /**
     * Constructor. It is private since utility classes should not have a public or default constructor.
     */
    private NGSIConstants() {
    } // NGSIConstants
} // NGSIConstants
